server:
  port: 8090
  servlet:
    context-path: /
  error:
    whitelabel.enabled: true
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always
  forward-headers-strategy: NATIVE

logging:
  config: 'classpath:logback-dev.xml'

spring:
  config:
    activate:
      on-profile: 'dev'

  jpa:
    show-sql: true

  datasource:
    url: jdbc:mariadb://HOST:3306/DB_NAME?useUnicode=true&characterEncoding=UTF-8&autoreconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username:
    password:

app:
  security:
    #auth-uri-filter-path: j_spring_cas_security_check
    #redirect-param-name: spring-security-redirect
    #security: http://URL:PORT/j_spring_cas_security_check
    authorized-domain-names:
      - http://localhost:8090
    protocol: http://
    id-key-provider:

  cas:
    url-prefix:
    url-login:
    url-logout:

  cors:
    allowed-origins:
      - http://localhost:5173

  admins:
    user-name:
    group-name: ''

  users:
    group-name: ''

  mail:
    base-url: http://localhost:8090
    from: glc@localhost

  authorized-services:
    ip-ranges:

  metrics:
    prometeus-authorized-acess:
      ip-ranges:

  ldap:
    context-source:
      base:
      urls:
        - ldap://HOST:389/
      username:
      password:
      anonymous-read-only: false
      native-pooling: false

    ldap-template:
      count-limit: 20000
      time-limit: 20000

    user-branch:
      other-displayed-attributes:
      other-backend-attributes:

    group-branch:
      dn-contains-display-name:
      other-displayed-attributes:
      group-member-key-pattern: ''
      group-member-key-pattern-index:
      user-member-key-pattern: ''
      user-member-key-pattern-index:
      group-display-name-pattern: ''
      resolve-user-members:
      resolve-user-members-by-user-attributes:
      # designers can be commented - used to attach groups that are not in the tree root or membrers on
      designers:
        - group-root-pattern: ''
          group-attach-end-match: ''
          group-to-attach-end-pattern: ''
        - group-root-pattern: ''
          group-attach-end-match: ''
          group-to-attach-end-pattern: ''
        - group-root-pattern: ''
          group-attach-end-match: ''
          group-to-attach-end-pattern: ''
      # for formatters can be commented
      name-formatters:
        - group-matcher: ''
          group-name-regex: ''
          group-name-index: ''
          group-recomposer-separator: ''
        - group-matcher: ''
          group-name-regex: ''
          group-name-index: ''
          group-recomposer-separator: ''
        - group-matcher: ''
          group-name-regex: ''
          group-name-index: ''
          group-recomposer-separator: ''
        - group-matcher: ''
          group-name-regex: ''
          group-name-index: ''
          group-recomposer-separator: ''
          group-suffixe-to-append: ''
        - group-matcher: ''
          group-name-regex: ''
          group-name-index: ''
          group-recomposer-separator: ''
          group-suffixe-to-append: ''
      dont-resolve-members-with-group-pattern: ''
      structure-properties:
        structure-from-group-pattern: ''
        filter-groups-of-structure: ''
        structure-categories-patterns:
          Etablissement: ''
          Collectivite_locale: ''
          Service_academique: ''
        uai-pattern: ''

  front:
    end-function-warning:

    staff:
      teaching:
      school:
      collectivity:
      academic:

    edit-allowed-states:
      -

    filter-account-states:
      -

    template-api-path: ''

    extended-uportal:
      header:
        component-path: ''
        props:
          context-api-url: ''
          sign-out-url: ''
          default-org-logo-path: ''
          default-avatar-path: ''
          default-org-icon-path: ''
          favorite-api-url: ''
          layout-api-url: ''
          organization-api-url: ''
          portlet-api-url: ''
          user-info-api-url: ''
          user-info-portlet-url: ''
          session-api-url: ''
          template-api-path: ''
          switch-org-portlet-url: ''
          favorites-portlet-card-size: ''
          grid-portlet-card-size: ''
          hide-action-mode: ''
          show-favorites-in-slider: ''
          return-home-title: ''
          return-home-target: ''
          icon-type: ''

      footer:
        component-path: ''
        props:
          template-api-path: ''

    login-offices:
      - source: ''
        guichets:
          - nom: ''
            categories-personne:
              -

  custom-config:
    suppress-days:

    alerts:
      - source: ''
        fonction-alerts:
          - code: ''
            min:
              value:
              type: error
              action: true
            max:
              value:
              type: error
              action: false
