server:
  port: 8090
  servlet:
    context-path: /
  error:
    whitelabel.enabled: true
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always
  forward-headers-strategy: NATIVE

logging:
  config: "classpath:logback-dev.xml"

spring:
  config:
    activate:
      on-profile: "dev"

  jpa:
    show-sql: true

  datasource:
    url: jdbc:mariadb://HOST:3306/DB_NAME?useUnicode=true&characterEncoding=UTF-8&autoreconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username:
    password:

app:
  security:
    #auth-uri-filter-path: j_spring_cas_security_check
    #redirect-param-name: spring-security-redirect
    #security: http://URL:PORT/j_spring_cas_security_check
    authorized-domain-names: >
      http://localhost:8090,
    protocol: http://
    id-key-provider:

  cas:
    url-prefix:
    url-login:
    url-logout:

  cors:
    allowed-origins: >
      http://localhost:5173

  admins:
    user-name:
    group-name: 'esco:admin:central'

  users:
    group-name: '([^:]+):admin:(local|central|ESCOLAN):?(?>[^:]+_(\d{7}[^:]))?'

  mail:
    base-url: http://localhost:8090
    from: glc@localhost

  authorized-services:
    ip-ranges:
      - '10.209.27.0/24'
      - '10.209.28.0/24'
      - '10.209.31.0/24'

  metrics:
    prometeus-authorized-acess:
      ip-ranges:
        - '10.209.27.0/24'
        - '10.209.28.0/24'
        - '10.209.31.0/24'

  ldap:
    context-source:
      base:
      urls:
        - ldap://HOST:389/
      username:
      password:
      anonymous-read-only: false
      native-pooling: false

    ldap-template:
      count-limit: 20000
      time-limit: 20000

    user-branch:
      other-displayed-attributes: mail, ESCOUAI, ENTPersonProfils
      other-backend-attributes: isMemberOf, ENTPersonProfils, ESCOPersonProfils, ENTPersonJointure, ESCOUAICourant, ESCOSIRENCourant

    group-branch:
      dn-contains-display-name: true
      other-displayed-attributes: isMemberOf
      group-member-key-pattern: 'cn=(.*),ou=groups,dc=esco-centre,dc=fr'
      group-member-key-pattern-index: 1
      user-member-key-pattern: 'uid=(.*),ou=people,dc=esco-centre,dc=fr'
      user-member-key-pattern-index: 1
      group-display-name-pattern: '.*:([^:]*)'
      resolve-user-members: true
      resolve-user-members-by-user-attributes: true
      # designers can be commented - used to attach groups that are not in the tree root or membrers on
      designers:
        - group-root-pattern: '((esco)|(cfa)|(clg[0-9]{2})|(agri)):Etablissements:[^:]*'
          group-attach-end-match: ':Profs'
          group-to-attach-end-pattern: ':*:Profs_*,:*:Profs Principaux'
        - group-root-pattern: 'ef2s:Etablissements:[^:]*'
          group-attach-end-match: ':Formateurs'
          group-to-attach-end-pattern: ':*:Formateurs_*, :*:Responsable de formation'
        - group-root-pattern: '((esco)|(cfa)|(clg[0-9]{2})|(agri)):Inter_etablissements'
          group-attach-end-match: ':Tous_Profils_Etablissements'
          group-to-attach-end-pattern: ':Tous_Profs,:Tous_Administratifs,:Tous_Eleves,:Tous_Parents,:Tous_Agents_Coll_Ter'
      # for formatters can be commented
      name-formatters:
        - group-matcher: '((esco)|(cfa)|(clg[0-9]{2})|(agri)|(ef2s)):Etablissements:[^:]+_[0-9]{7}[a-zA-Z]{1}:groupes_locaux:Publication_contenus'
          group-name-regex: '[^:]+:Etablissements:([^:]+)_[0-9]{7}[a-zA-Z]{1}:(groupes_locaux):Publication_contenus'
          group-name-index: '2,1'
          group-recomposer-separator: ' - '
        - group-matcher: '((esco)|(cfa)|(clg[0-9]{2})|(agri)):Etablissements:[^:]+_[0-9]{7}[a-zA-Z]{1}:[^:]+:Profs Principaux'
          group-name-regex: '[^:]+:Etablissements:[^:]+:([^:]+):(Profs Principaux)'
          group-name-index: '2,1'
          group-recomposer-separator: ' - '
        - group-matcher: 'ef2s:Etablissements:[^:]+_[0-9]{7}[a-zA-Z]{1}:[^:]+:Responsable de formation'
          group-name-regex: 'ef2s:Etablissements:[^:]+:([^:]+):(Responsable de formation)'
          group-name-index: '2,1'
          group-recomposer-separator: ' - '
        - group-matcher: 'agri:Inter_etablissements:Tous_Profils_Etablissements'
          group-name-regex: 'agri:Inter_etablissements:(Tous_Profils_Etablissements)'
          group-name-index: '1'
          group-recomposer-separator: ' '
          group-suffixe-to-append: ' EA'
        - group-matcher: 'esco:Inter_etablissements:Tous_Profils_Etablissements'
          group-name-regex: 'esco:Inter_etablissements:(Tous_Profils_Etablissements)'
          group-name-index: '1'
          group-recomposer-separator: ' '
          group-suffixe-to-append: ' EN'
      dont-resolve-members-with-group-pattern: '((agri)|(esco)|(clg[0-9]{2})):Inter_etablissements:Tous_((Profs)|(Administratifs)|(Eleves)|(Parents)|(Agents_Coll_Ter)|(Profils_Etablissements))'
      structure-properties:
        structure-from-group-pattern: '([^:]+):([^:]+):(([^:_]+)(_(\d{7}[^:]+))?):Tous_[^:]+'
        filter-groups-of-structure: '(&(|(cn=*:Etablissements:*:tous*)(cn=*:Services_Academique:*:tous*))(!(cn=*:*:*:*:*)))'
        structure-categories-patterns:
          Etablissement: '((esco)|(clg[0-9]{2})|(agri)|(cfa)|(ef2s)):.*'
          Collectivite_locale: 'coll:.*'
          Service_academique: 'acad:.*'
        uai-pattern: '[^:]+:[^:]+:[^:]+_(\d{7}[a-zA-Z]):[^:]+'
