spring:
  config:
    activate:
      on-profile: 'default-config'

---

logging:
  config: 'classpath:logback.xml'

spring:
  application:
    name: GLC

  profiles:
    active: @spring.profiles.active@
    group:
      dev: dev
      test: test
      prod: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

app:
  cors:
    enable: true
    allow-credentials: true
    allowed-origins:
      - http://localhost:5173
      - https://*.giprecia.net
    exposed-headers:
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-headers:
      - content-type
      - authorization
      - x-com-persist
      - X-Auth-Token
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-methods:
      - GET,
      - PUT,
      - POST,
      - DELETE

  front:
    end-function-warning: 2

    staff:
      teaching: Enseignant
      school: Non_enseignant_etablissement
      collectivity: Non_enseignant_collectivite_locale
      academic: Non_enseignant_service_academique

    edit-allowed-states:
      - Invalide
      - Valide
      - Bloque

    filter-account-states:
      - Invalide
      - Valide
      - Bloque
      - Delete
      - Deleting
      - Incertain

  custom-config:
    suppress-days: 20
