server:
  port: 8090
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: 'prod'

  datasource:
    url: jdbc:mariadb://HOST:3306/DB_NAME?useUnicode=true&characterEncoding=UTF-8&autoreconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username:
    password:

app:
  security:
    #auth-uri-filter-path: j_spring_cas_security_check
    #redirect-param-name: spring-security-redirect
    #security: http://URL:PORT/j_spring_cas_security_check
    authorized-domain-names:
      - http://localhost:5173
    protocol: http://
    id-key-provider:

  cas:
    url-prefix:
    url-login:
    url-logout:

  cors:
    enable: true
    allowed-origins:
      - https://*.giprecia.net
