server:
  port: 8080
  servlet:
    context-path: /

logging:
  config: 'classpath:logback-dev.xml'

spring:
  config:
    activate:
      on-profile: dev

  cache:
    type: caffeine
    cache-names: fonctionAlerts, collectivites, etablissement, fonctions, personneFonctions, structureFonctions, typesFonctionFiliere, disciplines, personnesWithoutFunctions, personnesByEtablissement, personne, relations, stuctureDBById, personneLDAPByUid, typeFonctionFiliere, discipline, incertains
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=30m

  jpa:
    show-sql: true

  datasource:
    url: jdbc:mariadb://HOST:3306/DB_NAME?useUnicode=true&characterEncoding=UTF-8&autoreconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username:
    password:

app:
  redis:
    hostName:
    port:
    userName:
    password:
    databaseIndex: "0"
    mappingPrefix: "${spring.redis.namespace}:mapping"
    indexPrefix: "${spring.redis.namespace}:index"

  session:
    cron-allowed-hostname: ""
    cron-expression: 0 0 10 * * *


  restriction-rentree:
    url: http://HOST
    apiKey:

  grouper:
    base-url: http://HOST
    username:
    password:

  rights:
    services-path: 'file:'
    declared-groups:
      - grouper-path:
        display-name:

  admin:
    local:
    sarapis-local:
    central:
    central-coll:
    direction:
    groups-attribute:

  cas:
    cas-service-id:
    cas-server-url: http://HOST
    cas-provider-key: casProviderKey
    cas-ticket-callback: /login/cas

  cors:
    allowed-origins:
      - http://localhost:5173

  mail:
    base-url: http://localhost:8080
    from: glc@localhost

  authorized-services:
    ip-ranges:
      -

  metrics:
    prometeus-authorized-acess:
      ip-ranges:
        -

  uid-factory:
    default-code-generateur:
    domain-to-code-generateur:
      '':
    code-region:
    nom-source:
    nb-lettre-ann:
    nb-lettre-total:
    nb-lettre-inc:

  ldap:
    context-source:
      base:
      urls:
        - ldap://HOST:389/
      username:
      password:
      anonymous-read-only: false
      native-pooling: false

    ldap-template:
      count-limit: 20000
      time-limit: 20000

    user-branch:
      other-displayed-attributes:
      other-backend-attributes:

    structure-branch:
      base:
      all-structures-by-siren-filter:
      structures-coll-filter:

    group-branch:
      dn-contains-display-name:
      other-displayed-attributes:
      group-member-key-pattern: ''
      group-member-key-pattern-index:
      user-member-key-pattern: ''
      user-member-key-pattern-index:
      group-display-name-pattern: ''
      resolve-user-members:
      resolve-user-members-by-user-attributes:
      dont-resolve-members-with-group-pattern: ''
      structure-properties:
        structure-from-group-pattern: ''
        filter-groups-of-structure: ''
        structure-categories-patterns:
          Etablissement: ''
          Collectivite_locale: ''
          Service_academique: ''
        uai-pattern: ''

  front:
    default-structure-image:
    default-user-image:
    end-function-warning:

    staff:
      teaching:
      school:
      collectivity:
      academic:

    edit-allowed-states:
      -

    filter-account-states:
      -

    extended-uportal:
      header:
        component-path: ''
        props:
          template-api-path: ''
          fname: ''
          dnma-url: ''

      footer:
        component-path: ''
        props:
          template-api-path: ''

  custom-config:
    pronote-group-regex:
    suppress-days:

    alerts:
      - source: ''
        fonction-alerts:
          - filiere: ''
            discipline: ''
            min:
              value:
              type: error
              action: true
            max:
              value:
              type: error
              action: false

    login-offices:
      - source: ''
        guichets:
          - nom: ''
            categoriesPersonne:
              -

    fonctions:
      - source: ''
        filieres:
          - code: ''
            disciplines:
              - ''
            admin: true
        disciplines:
          - ''
