spring:
  config:
    activate:
      on-profile: 'default-config'

---

server:
  port: 8090
  servlet:
    context-path: /spring-api

#logging:
#  level:
#    web: DEBUG
#    fr: DEBUG

spring:
  application:
    name: GLC

  profiles:
    active: @spring.profiles.active@
    group:
      dev: dev
      test: test
      prod: prod
      ci: test

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

security-configuration:
  soffit:
    jwt.signatureKey: "=== Signature Key ==="

  cors:
    enable: true
    allow-credentials: true
    allowed-origins: >
      http://localhost:5173,
      https://*.giprecia.net
    exposed-headers: >
      x-auth-token,
      x-requested-with,
      x-xsrf-token
    allowed-headers: >
      content-type,
      authorization,
      x-com-persist,
      X-Auth-Token,
      x-auth-token,
      x-requested-with,
      x-xsrf-token
    allowed-methods: >
      GET,
      PUT,
      POST,
      DELETE

app:
  config:
    filiere:
      administrative: >
        DIR,
        ADF,
        CTR,
        EDU,
        MDS,
        PSY,
        ADM,
        AED
      teaching: >
        ACP,
        APP,
        DOC,
        DCT,
        ENS,
        FCA,
        FIJ,
        REM,
        STG
