server:
  port: 8090
  servlet:
    context-path: /api-quentin

spring:
  config:
    activate:
      on-profile: "test"

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/sarapis_test?useUnicode=true&characterEncoding=UTF-8&autoreconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username: root
    password: root

  ldap:
    url:
    base:
    username:
    password:

security-configuration:
  cas:
    id-key-provider:
    service:
    url:
      prefix:
      login:
      logout:

  cors:
    enable: true
    allowed-origins: >
      http://localhost:5173,
      http://10.209.28.14:5173,
      https://*.giprecia.net
