server:
  port: 8090
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: 'prod'

  datasource:
    url: jdbc:mariadb://HOST:3306/DB_NAME?useUnicode=true&characterEncoding=UTF-8&autoreconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username:
    password:

security-configuration:
  soffit:
    jwt.signatureKey: ""

  cors:
    enable: true
    allowed-origins: >
      https://*.giprecia.net
