server:
  port: 8090
  servlet:
    context-path: /api-quentin

#logging:
#  level:
#    web: DEBUG
#    fr: DEBUG

spring:
  config:
    activate:
      on-profile: "test"

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/sarapis_test?useUnicode=true&characterEncoding=UTF-8&autoreconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username: root
    password: root

security-configuration:
  soffit:
    jwt.signatureKey: ""

  cors:
    enable: true
    allowed-origins: >
      http://localhost:5173,
      http://10.209.28.14:5173,
      https://*.giprecia.net
